packages:
  - apps/*
  - packages/*
  - tooling/*
  - scripts

catalog:
  "@better-auth/expo": 1.4.0-beta.9
  "@better-auth/cli": 1.4.0-beta.9
  "@biomejs/biome": ^2.2.5
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": ^5.90.8
  '@tailwindcss/postcss': ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  "@trpc/client": ^11.7.1
  "@trpc/server": ^11.7.1
  "@trpc/tanstack-react-query": ^11.7.1
  "@types/node": ^24.6.2
  '@vitest/coverage-v8': ^4.0.0
  "@vitejs/plugin-react": 5.1.0
  tsx: ^4.20.6
  better-auth: 1.4.0-beta.9
  execa: ^9.6.0
  nativewind: ^5.0.0-preview.1
  postcss: ^8.5.6
  react-native-safe-area-context: ^5.4.1
  react-native-reanimated: 4.1.2
  react-native-worklets: 0.6.0
  react-native-css: 3.0.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.16
  tailwindcss-safe-area: ^1.1.0
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  zod: ^4.1.12
  vite: 7.1.12


catalogs:
  react19:
    '@types/react': 19.1.0
    '@types/react-dom': 19.1.0
    react: 19.1.0
    react-dom: 19.1.0
    react-native-renderer: 19.1.0

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

# publicHoistPattern:
#   - "@ianvs/prettier-plugin-sort-imports"
#   - prettier-plugin-tailwindcss
