packages:
  - apps/*
  - packages/*
  - tooling/*
  - scripts

catalog:

  "@better-auth/expo": 1.4.0-beta.9
  "@better-auth/cli": 1.4.0-beta.9
  "@biomejs/biome": ^2.2.5
  "@tanstack/react-form": ^1.23.7
  "@tanstack/react-query": ^5.90.2
  '@tailwindcss/postcss': 4.1.14
  '@trpc/client': ^11.6.0
  '@trpc/server': ^11.6.0
  "@trpc/tanstack-react-query": ^11.6.0
  '@types/node': ^22.15.29
  '@vitest/coverage-v8': ^4.0.0
  tsx: ^4.20.6
  better-auth: 1.4.0-beta.9
  execa: ^9.6.0
  nativewind: ^5.0.0-preview.1
  postcss: ^8.5.6
  react-native-safe-area-context: ^5.4.1
  react-native-reanimated: 4.1.2
  react-native-worklets: 0.6.0
  react-native-css: ^3.0.0-preview.5
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  tailwindcss-safe-area: ^1.1.0
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  zod: ^4.1.12


catalogs:
  react19:
    '@types/react': 19.1.0
    '@types/react-dom': 19.1.0
    react: 19.1.0
    react-dom: 19.1.0
    react-native-renderer: 19.1.0

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild

overrides:
  "@types/minimatch": 5.1.2

# publicHoistPattern:
#   - "@ianvs/prettier-plugin-sort-imports"
#   - prettier-plugin-tailwindcss
